services:
  mongo-db:
    image: mongo:6.0.26-jammy
    container_name: mongo_db
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_DATABASE: championship-db
      MONGO_INITDB_ROOT_USERNAME: dcalvi
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo:/data/db
