services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile

    image: championship-docker
    container_name: championship-docker

    restart: unless-stopped # reiniciar el contenedor si se detiene

    depends_on:
      mongo-db:
        condition: service_healthy

    ports:
      - '${PORT}:${PORT}'

    environment:
      NODE_ENV: production
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_DB: ${MONGO_DB}
      NAME_DB: ${NAME_DB}

  mongo-db:
    image: mongo:8
    container_name: mongo-championship
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: championship-db
      MONGO_INITDB_ROOT_USERNAME: dcalvi
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
